select * from JOBS;

select * FROM JOB_HISTORY;

select JOB_TITLE, JOB_HISTORY.JOB_ID from JOBS
inner join JOB_HISTORY
on JOBS.JOB_ID = JOB_HISTORY.JOB_ID;


select * from LOCATIONS;
select * from COUNTRIES;

select STREET_ADDRESS, POSTAL_CODE, CITY, COUNTRY_NAME FROM LOCATIONS
inner join COUNTRIES
on LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID;

