SELECT * FROM EMPLOYEES;

SELECT COUNT(FIRST_NAME) FROM EMPLOYEES;

SELECT COUNT(REGION_ID) FROM REGIONS;

-- COUNT statement no Null
SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY, PHONE_NUMBER FROM EMPLOYEES;

SELECT DISTINCT JOB_ID FROM EMPLOYEES;

SELECT JOB_ID FROM EMPLOYEES;





