SELECT FIRST_NAME FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE FIRST_NAME = 'David';

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > 5000;

SELECT LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY <= 3000;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY != 10000;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY <> 10000;

SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES;

SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES
WHERE JOB_ID='ST_CLERK' OR JOB_ID = 'IT_PROG';

SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY, JOB_ID FROM EMPLOYEES
where JOB_ID = 'IT_PROG' AND SALARY = '4800';

SELECT POSTAL_CODE, COUNTRY_ID FROM LOCATIONS
WHERE COUNTRY_ID = 'JP' OR COUNTRY_ID = 'UK' OR COUNTRY_ID = 'CA';



